### ISSUE TITLE
reader tamper state

### ISSUE THREAD

**Issue by s3r4fin** [goToMain/libosdp#105]
The requirement is get current state of tamper and receive event when tamper state changes.

Related LSTAT command & LSTAT response seems dropped on libosdp library.

**Comment by sidcha** [comment]
@s3r4fin local status reports (`CMD_LSTAT`, `REPLY_LSTATR`) are now supported using the PD events API. Look for `OSDP_EVENT_STATUS`.

**Comment by s3r4fin** [comment]
Thank you so much! Event works fine! 
Can CP ask for tamper status on start?

**Comment by s3r4fin** [comment]
Thank you! It works
