### ISSUE TITLE
Incorrect handling of length in CMD_ABORT

### ISSUE THREAD

**Issue by surendersampath** [goToMain/libosdp#109]
**Describe the bug**
In the PD side, the length is handled incorrectly for a zero length command. CMD_ABORT is a zero length command just like CMD_POLL. Hence, its length should be checked similarly as it's being done in CMD_POLL.

**Expected behavior**
![image](https://user-images.githubusercontent.com/44113702/223787366-4fbf6698-2a3a-4ec8-af7a-7a26c670a375.png)
**Observed behavior**
![image](https://user-images.githubusercontent.com/44113702/223787266-f8df48a4-9152-4e03-bfd2-ff17478ead3f.png)

[1]: https://libosdp.gotomain.io/libosdp/debugging.html

**Comment by sidcha** [comment]
Thanks for reporting it.

Btw, you could have created a PR for this change in half the time it took to create this issue. I'm not complaining, just saying :).

**Comment by surendersampath** [comment]
Thanks. Will do it next time. Cheers.
