### ISSUE TITLE
Enhance Python API to not expose bit masks

### ISSUE THREAD

**Issue by Stuckya** [goToMain/libosdp#114]
**Describe the bug**
The Python bindings no longer expose `is_sc_active()`
The sample code encourages users to call a missing method on line 105 of `cp_app.py:`

```python
    if (count % 100) == 99 and cp.is_sc_active(PD_0):
```

**Expected behavior**
The ability to educate users of this library which python method to call for checking if a PD is active.

**Observed behavior**
Runtime error when attempting to run the sample.

**Additional context**
While trying to find alternatives, the following code was successful:

```python
    if (count % 100) == 99 and bool(cp.sc_status() & 1 << PD_0):
```

Will open a PR to fix.

**Comment by sidcha** [comment]
Will keep this issue open to track the change: enhance the API to abstract bitmask details.

**Comment by sidcha** [comment]
This will be handled in a different approach. The idea is to promote [tests/pytest/testlib](https://github.com/goToMain/libosdp/tree/c932fbebdc481ac7cb1a98f5c4410df83a75ec1a/tests/pytest/testlib) into a proper python module. Closing this for now.

**Comment by sidcha** [comment]
This will be handled in a different approach. The idea is to promote [tests/pytest/testlib](https://github.com/goToMain/libosdp/tree/c932fbebdc481ac7cb1a98f5c4410df83a75ec1a/tests/pytest/testlib) into a proper python module. Closing this for now.
