### ISSUE TITLE
Building with libc other than glibc (execinfo.h)

### ISSUE THREAD

**Issue by jmlzr** [goToMain/libosdp#127]
Building with a libc different than glibc - like e.g. musl - failes since `execinfo.h` is not available there.

This was patched in https://github.com/goToMain/c-utils/commit/236a50cd7de7393a2eee073d419f4650ff236461 but the c-utils subrepo was never updated even though that commit is a lot older then the last libosdp release - which is why I'm opening this report here. Also that patch is problematic since the changes to `channel.c` are IMHO not just unnecessary but break functionality.
I patch only the single line in `utils.c` on my side.

Since embedded Linux - where using a other libc than glibc is very popular - is probably a common platform for this library it would be nice to get this fixed asap.

**Comment by sidcha** [comment]
> This was patched in https://github.com/goToMain/c-utils/commit/236a50cd7de7393a2eee073d419f4650ff236461 but the c-utils subrepo was never updated even though that commit is a lot older then the last libosdp release

Indeed, fixed that now. 

> Also that patch is problematic since the changes to channel.c are IMHO not just unnecessary but break functionality.

Right, the doc says `struct msgbuf` has to be user defined; didn't check the doc when I merged that PR. Thanks for reporting this, fixed now.
