### ISSUE TITLE
How to build libosdp for Android platform

### ISSUE THREAD

**Issue by HiLittlePiper** [goToMain/libosdp#128]
Hello,

I want to compile this library for Android App, but I did not find any introduction out in the documentation, do you have any introduction to guide how to build Android library?

Thanks

**Comment by sidcha** [comment]
I haven't done this but I don't think it should be a problem. It should be fairly straightforward to compile with Android's NDK build. Please follow the plain make build (./configure.sh && make) and adapt it to your Android.mk file.

**Comment by sidcha** [comment]
@HiLittlePiper, have you had any luck with this? You can still use this issue page to ask help or post findings. Thought I am no expert on android NDK builds, I will try my best to help you with any libosdp specific issues you may have.
