### ISSUE TITLE
porting libOSDP to STM32 without queues?

### ISSUE THREAD

**Issue by MatTab3335** [goToMain/libosdp#132]
I want to run OSDP lib on STM32, but without using any RTOS, so the problem is in queues, is it possible somehow run this lib without queue.h ?

**Comment by sidcha** [comment]
I don't see the connection, sorry; queue.h depends on list.h and both list.c and queue.c don't impose any OS specific requirements so you should be able to compile it to bare-metal. Can you please elaborate how queue.h is causing issues for you?

**Comment by MatTab3335** [comment]
I'm sorry, instead of "slab", I wrote "queue". So the problem is to use slab functions and structures, I can't find anything similar to use with stm32

**Comment by sidcha** [comment]
Slab also does not depend on anything OS specific.

Most of the modules in [c-utils repo](https://github.com/goToMain/c-utils/ ) is written to be OS independent. All you have to do is build a subset of that repository for STM32 and then build libosdp along with it.

**Comment by MatTab3335** [comment]
Ok, thank you, I'll try

**Comment by sidcha** [comment]
I will close this issue for now, please keep the conversation going if need be.

**Comment by vk2tds** [comment]
I am currently running the library on an STM32F411 under Arduino, and it is working fairly well. https://github.com/vk2tds/libosdp_arduino
