### ISSUE TITLE
PD offline is a little aggressive

### ISSUE THREAD

**Issue by rm5248** [goToMain/libosdp#140]
**Describe the bug**
With the fix for #133, we are occasionally getting an indication on the PD side that the connection has dropped, when our CP side is not detecting a drop.

The default timeout is set to [200ms here](https://github.com/goToMain/libosdp/blob/aaa303b0ce0d2b79bd2e98061bf6084f1ed6dfb3/src/osdp_common.c#L267).  The 200ms is how long a single PD needs to respond within.  Several options to fix:

1. Increase the delay to at least 600ms.  Note that in the OSDP spec version 2.2 and 2.1.7, the "off-line" time is set to 8 seconds, so that is probably the correct time to set it to.
2. Add an option to make this configurable on the PD side(e.g. `osdp_pd_set_max_offline_time`)

**Comment by sidcha** [comment]
@rm5248, thanks for reporting this. I have added a new macro `OSDP_ONLINE_TOUT_MS` defined to 600 ms. 8 seconds seem too high a number for my preference :).
