### ISSUE TITLE
How does a PD answer to CMD_ISTAT?

### ISSUE THREAD

**Issue by Sympatron** [goToMain/libosdp#154]
A `CMD_ISTAT` command from the CP triggers this code in the PD: https://github.com/goToMain/libosdp/blob/4394508e09e97c96c7a2f822d882902e213adda4/src/osdp_pd.c#L735-L746

This expects the correct input status event to be in `pd->ephemeral_data`. How is the input status data supposed to get there?

`CMD_ISTAT` and `CMD_OSTAT` do not trigger any user code as far as I can see.

**Comment by sidcha** [comment]
Right, there is no way to do this now. Will fix it, thanks for reporting it.
