### ISSUE TITLE
Undefined reference if linking against static library

### ISSUE THREAD

**Issue by rherrmannr** [goToMain/libosdp#169]
**Describe the bug**
Undefined reference if linking against static library.

**Expected behavior**
It should be possible to link against the static library. All references must be resolved.

**Observed behavior**
No object files for `osdp_pcap.c` and `pcap_gen.c`. They should be added to `LIB_OSDP_SOURCES` instead of `LIB_OSDP_UTILS_SRC`:

```cmake
if (CONFIG_OSDP_PACKET_TRACE OR CONFIG_OSDP_PACKET_TRACE)
	list(APPEND LIB_OSDP_SOURCES
		${CMAKE_CURRENT_SOURCE_DIR}/osdp_pcap.c
	)
endif()

# and later on:
if (CONFIG_OSDP_PACKET_TRACE OR CONFIG_OSDP_PACKET_TRACE)
	list(APPEND LIB_OSDP_SOURCES
		${PROJECT_SOURCE_DIR}/utils/src/pcap_gen.c
	)
endif()
```

**Additional context**
Config using CMake:
```cmake
set(CONFIG_OSDP_PACKET_TRACE ON)
set(CONFIG_OSDP_DATA_TRACE OFF)
set(CONFIG_OSDP_SKIP_MARK_BYTE OFF)
set(CONFIG_DISABLE_PRETTY_LOGGING OFF)
set(CONFIG_OSDP_STATIC_PD OFF)
set(CONFIG_OSDP_LIB_ONLY ON)
```
**A Comprehensive Log file**
```
/usr/bin/ld: ../mylib.so: undefined reference to `osdp_packet_capture_init'
/usr/bin/ld: ../mylib.so: undefined reference to `osdp_capture_packet'
/usr/bin/ld: ../mylib.so: undefined reference to `osdp_packet_capture_finish'
```

[1]: https://libosdp.sidcha.dev/libosdp/debugging.html

**Comment by sidcha** [comment]
@rherrmannr please feel free to re-open this issue if does not fix your problem. I didn't test this fix, just eye-balled :)
