### ISSUE TITLE
v3.0.6 is restarting SC twice after KEYSET

### ISSUE THREAD

**Issue by sebastianedse** [goToMain/libosdp#193]
**Describe the bug**
When a new PD is connected, the SCBK-D will be used and KEYSET command will write the new SCBK to the device. After this has been done the stack restarts with SC_CHLNG twice.

**Expected behavior**
I expect it to only restart once.

**Additional context**
I assume this has to do with the CP_REQ_RESTART_SC request in cp_keyset_complete(). Is it maybe a leftover from last state machine?
And a side note: the function cp_keyset_complete() is called twice in the new state machine (this is not causing this bug, but), is this really intended? It seems that it prints two LOG_INF and deactivates sc twice...

**Comment by sidcha** [comment]
Closing as not reproducible. If you have more details, feel free to re-open this issue.
