### ISSUE TITLE
Support install mode lock down for the CP

### ISSUE THREAD

**Issue by te-johan** [goToMain/libosdp#21]
The install mode works well for the PD end today, however the CP will always switch to SCBK-D if SCBK do not work.
I think it would be good to have some sort of lock down flag to disallow both unencrypted and SCBK-D.

For application design it could be good enough to just pass that flag to osdp_cp_setup()

**Comment by cbsiddharth** [comment]
This is a nice idea! pd_info_t has a flags field that was intended for this kind of use-cases. We can introduce a `OSDP_FLAG_ARMOR` or `OSDP_FLAG_SECURE` to achieve this.

I wonder how we can pass these flags from python neatly.
