### ISSUE TITLE
ENFORCE_SECURE has no effect for PDs

### ISSUE THREAD

**Issue by te-johan** [goToMain/libosdp#29]
When the enforce secure flag is set for PDs it has no real effect.
If a CP does not setup an encryption it will remain unencrypted.
a reasonable approach would be to only allow some unencrypted messages to be processes by the PD.
The ID, Capability and the encryption initialization messages would probably suffice.

**Comment by cbsiddharth** [comment]
Fixed in: e46aa0f1
