### ISSUE TITLE
OSDP_EVENT_FILE_TX missing implementation

### ISSUE THREAD

**Issue by laszlopataki** [goToMain/libosdp#74]
Hi, thank you for the great lib

**Describe the bug**
I am implementing a PD firmware update. 
I transfer the image and the signature via multiple FILETRANSFER commands. 
After this, the PD reboots and does a self-check. 
Finally, PD would report back to CP with OSDP_EVENT_FILE_TX. 

- osdp_event_file_tx is missing from `osdp.h:osdp_event` it is missing from the doxygen @params section. 
- OSDP_EVENT_FILE_TX is missing from `osdp_pd.c:pd_translate_event` as a result PD prints "Unknown event type 3"

**Expected behavior**
I am able to use OSDP_EVENT_FILE_TX to report the result of the firmware update to CP. 

**Observed behavior**
PD prints "Unknown event type 3"

**Additional context**
I am using v2.0.0 release. 
I purchased the standard document. 
I was wondering what OSDP_EVENT_FILE_TX is equivalent in `SIA-OSDP-2.2-FINAL-120720.pdf`

**Comment by sidcha** [comment]
Hey @laszlopataki, `OSDP_EVENT_FILE_TX ` should not exits, it was part of another design I was considering at the time and missed to remove it fully. :)

According to the spec, the CP has to send a EOF packet with the `offset` set to `file_size` and `length` set to 0. When the PD receives and acknowledges it, both parties know that the transmission session has ended so there is no need to send an explicit notification to the CP.
