### ISSUE TITLE
Confusing `temporary` flag in Python LED commands

### ISSUE THREAD

**Issue by Tomcat-Engineering** [goToMain/libosdp#79]
**Describe the bug**

Here is how you set the state of the LEDs temporarily:

```python
control_panel.send_command(0, {"command": osdp.CMD_LED, ... "temporary": True})
```

However, this command also sets the state of the LEDs temporarily:

```python
control_panel.send_command(0, {"command": osdp.CMD_LED, ... "temporary": False})
```

This is because the code is just looking for the *existence* of the `temporary` flag, not its value.  Not sure whether this is intentional but it definitely caught me out and took me a couple of hours to figure out!

**Expected behavior**

Setting `"temporary": False` in an LED command updates the permanent state of the LEDs, not the temporary state.

**Observed behavior**

Setting `"temporary": False` in an LED command updates the temporary state of the LEDs, not the permanent state.

**Comment by sidcha** [comment]
Sorry about that. That is indeed wrong behaviour. Let me take a quick look.
