### ISSUE TITLE
External Logger port support

### ISSUE THREAD

**Issue by bryanvalletta** [goToMain/libosdp#80]
We're integrating this library into our embedded application, and it would be nice to be able to use our currently implemented logging (just console) mechanism to output libosdp messages out-of-box. So offering a way to configure the library to use a logger port would be very useful.

Thanks!

**Comment by sidcha** [comment]
Hey, this is already supported :). Have a look at `osdp_logger_init` which takes `osdp_log_puts_fn_t` ([doc](https://libosdp.gotomain.io/api/miscellaneous.html#_CPPv416osdp_logger_initi18osdp_log_puts_fn_t)). Let me know if that doesn't fit your use case for some reason.

**Comment by bryanvalletta** [comment]
I think our specific issue is that we use a logging framework that's actually very similar to what is built into libOSDP (we actually run into build issues when compiling - multiple function definitions). So if there is a way to define a port for all the logging macros that would be useful for our use case.

**Comment by sidcha** [comment]
Ah, I see. Which project/environment are you building LibOSDP in? Maybe the namespace "logger_" in utils/logger.c is too generic. Can you provide the build logs so I can see what sort of conflicts these are? If it is a known popular project/environment, I can try to refactor names in LibOSDP so they don't conflict there.

Alternatively, you can come up with a solution that works for you and send a PR here so I can review your changes. :)

**Comment by bryanvalletta** [comment]
We're building as a part of a C application using CMake and ARM GCC.

And maybe I will do that haha, I have already forked and made some changes to get them to play nicely, so I can just clean that up a bit!

Also while I have you and unrelated, is there API docs I can reference for the python implementation (specifically for the ControlPanel)?

**Comment by sidcha** [comment]
Unfortunately no. I haven't gotten around to documenting it yet. The python sample [cp_app.py](https://github.com/goToMain/libosdp/blob/master/samples/python/cp_app.py) should give you an idea of how to use the module. You can also have a look at the list of methods [here](https://github.com/goToMain/libosdp/blob/master/python/pyosdp_cp.c#L338-L354) and each of those methods have a doc string right above it which may provide some insights.

Just an FYI, there two kind/levels of Python support right now (honestly I don't know which is better, at different times either looks better than the other). Inside [python/](https://github.com/goToMain/libosdp/tree/master/python) there is a python-c-bindings module that exposes the raw C API over python with some (un)marshalling of C structures to python dicts. Here, you should find 1-1 python calls for the C methods. After this was developed, for ease of testing with pytest, I wrote some wrappers on top of this module that does some more device lifecycle management; this can be found at [pytest/testlib/](https://github.com/goToMain/libosdp/tree/master/pytest/testlib). Feel free to choose the one that best fits your need/taste.

**Comment by bryanvalletta** [comment]
This is all great info thank you! I will also close this issue and take a stab at implementing the logger framework port as well.
