### ISSUE TITLE
Python.h file missing

### ISSUE THREAD

**Issue by kenhun93** [goToMain/libosdp#92]
Hi, I currently trying to build python and cant seem to find the python.h file in the build directory nor in the github repo?
Am i missing something, or is the file actually missing?

![image](https://user-images.githubusercontent.com/5854964/203154343-9200c53f-940f-4b90-b6e4-3ca16badbd93.png)

**Comment by sidcha** [comment]
@kenhun93, you need to install the python3 development package (python3-dev on Ubuntu) to get that header.
