### ISSUE TITLE
Incorrect command ID to instruct a PD to abort on current operation.

### ISSUE THREAD

**Issue by surendersampath** [goToMain/libosdp#93]
**Describe the bug**
Incorrect command ID to instruct a PD to abort on current operation (File Transfer for example).

**Expected behavior**

CP device to send abort command with `osdp_ABORT `COMMAND ID `0xA2`. As per `OSDP V2.2`. 

![image](https://user-images.githubusercontent.com/44113702/203384443-339b6d23-d5c4-4e0b-82e5-0db6dce15a46.png)

**Observed behavior**
Library is sending 7A  which is `osdp_FTSTAT`. This is not per `OSDP V2.2`. 

![image](https://user-images.githubusercontent.com/44113702/203385933-1ead3792-a894-4bf8-aa52-fd4af4d4d30c.png)

**Additional context**

The context is OTA file transfer between CP and PD. CP wants to abort the file transfer.

[1]: https://libosdp.gotomain.io/libosdp/debugging.html

**Comment by sidcha** [comment]
@surendersampath, Thanks for reporting the issue, fixed now.
