### ISSUE TITLE
OSDP_CMD_ABORT is not exposed to the application. 

### ISSUE THREAD

**Issue by surendersampath** [goToMain/libosdp#97]
**Describe the bug**
CMD_ABORT's command ID was fixed in issue #93 . However, this is not being exposed to the application.
Hence, not able to invoke abort command via `osdp_cp_send_command()` .
![image](https://user-images.githubusercontent.com/44113702/206508798-747a3d2b-e4b1-4b1b-a998-cda93e0e1fc2.png)

**Expected behavior**
`CMD_ABORT` to be exposed to application.

**Observed behavior**
`CMD_ABORT` is not exposed to application.

**Comment by sidcha** [comment]
@surendersampath, the OSDP defined command `CMD_ABORT` is not meant for external use by applications, libosdp abstracts those details and provides its own high level commands though `enum osdp_cmd_e`.

Something _is_ missing though: the file transfer API `osdp_file_tx_abort` should send CMD_ABORT to the peer before reseting the state. Do you have any other use case for why ABORT needs to be exposed to the application?

**Comment by surendersampath** [comment]
I would like to use the abort command to stop the ongoing file transfer. But, Do you suggest that just calling file_tx_abort() function is sufficient?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sidcha** [comment]
No, I spoke too soon, `osdp_file_tx_abort ` is an internal method and servers a different purpose.

After some inspection, I think it more sensible to abort an ongoing transfer using the existing `OSDP_CMD_FILE_TX` command's flags (`osdp_cmd_file_tx::flags`) field. Will make that change.

**Comment by sidcha** [comment]
@surendersampath, You can use the newly introduced bit `OSDP_CMD_FILE_TX_FLAG_CANCEL` in `osdp_cmd_file_tx::flags` to abort an ongoing transfer. PD will not receive this command directly (as with other commands); instead the CP will send OSDP command `CMD_ABORT` to PD to signal the premature termination of current file transfer.

There is also a test case to ensure its correctness, so I will close this issue. For the command build failure, I'll create a new issue to track it.
